
services:
  httpbin:
    # https://github.com/mccutchen/go-httpbin/blob/main/Dockerfile
    user: 1033:1033 # userid:groupid
    image: mccutchen/go-httpbin

  nodesvc:
    # user: 1036:1036 # <- this fails because os.userInfo() wants user record in /etc/passwd
    build: ./node-server/

  nginx:
    # https://hub.docker.com/_/nginx
    image: nginx:1.23.3-alpine
    ports:
    - 8082:8082
    user: 1035:1035
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
